### ISSUE TITLE
[WARNING] Netlify link?

### ISSUE THREAD

**Issue by johannpinson** [CeliaDagorne/hetic-p2020-05-SpringCanaberry#3]
I don't see any netlify/now.sh/gh-pages or another integration tool to have a testing URL of the project.

**Comment by CeliaDagorne** [comment]
here it is : https://spring-canaberry.herokuapp.com

**Comment by johannpinson** [comment]
Ok, don't forget to add it inside the README.md and the github repository informations.

I let you close the issue when it will be done.
